PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sbol2: <http://sbols.org/v2#> 

SELECT 
    ?object 
    ?name 
WHERE { 
    ?object a sbol2:Collection . 
    FILTER NOT EXISTS { ?otherCollection sbol2:member ?object } 
    OPTIONAL { ?object dcterms:title ?name . }
}